### ISSUE TITLE
UML을 만든 상태에서 User Story를 만드는 것은 오버헤드인가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#10]

**Comment by stevemg** [comment]
User Story가 고객의 요구사항을 도출을 위해 하는 과정인데, 우리는 이미 요구사항 도출을 넘어 UML작성까지 완료하였다. 이걸 완료하고 다시 고객의 요구사항 도출을 하는게 프로세스 과정을 다시 리턴을 하는게 오버헤드가 크게 발생할 거같다.

**Comment by Hann** [comment]
CRC와 UserStory없이 바로 UML만드는데에는 시간이 너무 오래 걸렸다. 만약 미리 만들고 갔다면 UML만드는 것은 금방 끝났을 것 같다.

**Comment by Hann** [comment]
디자인 모델 만들떄 스테이트 머신 다이어그램을 그렸는데
유저스토리를 대체하는 역할을 한 것 같음
