### ISSUE TITLE
페어프로그래밍 팀을 어떻게 구성해야 효율적이었는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#100]

**Comment by Hann** [comment]
페어프로그래밍은 원래 비슷한 실력의 사람을 페어로 지어줘야하는 것이라고 생각했는데
모두가 개발을 잘 할 수 있다는게 전제로 깔려있는 것 같다.
지금 팀을 짓는다면 내부에 이끌어갈 사람이 들어가도록 재분배 할 것 같다.

**Comment by jaeseung91** [comment]
비슷한 실력을 가진 사람들끼리 페어 프로그래밍을 했을 때 가장 좋은 결과가 난다고 했는데, 그것은 다들 일정 수준에 도달했을 때라는 전제가 깔린 것 같다. 배우는게 많을 경우에는 이끌어 나갈 수 있는 사람이 그룹에 한 명 씩은 포함되는 것이 프로젝트의 진행을 고려할 때 더 효율적일 것 같다.

**Comment by stevemg** [comment]
@jaeseung91 @Hann  의견과 같이 암묵적으로 전제가 깔려야 할거같다.
