### ISSUE TITLE
Travis를 쓰는게 나았는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#101]

**Comment by Hann** [comment]
커밋마다 옆에  v x가 떠서 프로젝트를 관리하는데 좋았다.

**Comment by jaeseung91** [comment]
커밋시 자동적으로 test를 해주면서 pass인지 fail인지 알 수 있기 때문에, 매번 자신이 test하는 수고를 덜 수 있었다.

**Comment by hsilnam** [comment]
내 컴퓨터에서 잘 돌아가는 코드가 실제로 잘 돌아가는지 commit하자마자 알고 고칠수 있어서 좋았다.

**Comment by shinsy1023** [comment]
백엔드 개발중엔 자동적으로 테스트가 계속 돌아가기 때문에 직접 실행시켜보면 되고, 팀원도 다른 한 명이 전부였기 때문에 다른 사람의 코드 상태를 모니터링 한다는 용도로는 잘 쓰이지 않았다.

**Comment by stevemg** [comment]
이것을 안썻다면 내 환경에서 test가 통과해서 커밋한 후에 서버에서 test pass라고 짐작할 수 있었겠지만, Travis를 사용함으로 서버에서 test를 한번 더 확인할 수 있어서 좋았다.
