### ISSUE TITLE
이슈가 잘 공유되지 않았던 이유는 무엇일까?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#102]

**Comment by Hann** [comment]
백엔드는 물리적으로 가까워서 그리고 자람이여서 회의를 볼 수 있는 시간이 많아서 개입이 많았는데,
프론트엔드는 회의를 본게 몇번 없었다. 그래서 내부적으로 나온 이슈를 듣지 못하고 외적으로만 들었던게 문제인 것 같다.

**Comment by jaeseung91** [comment]
자존심과 책임감 때문에 내가 맡은 것은 내가 끝내야겠다는 생각 하에 계속 찾아보고 공부를 하였다. 어느 정도 진전이 없으면 팀원에게 요청을 했어야 하는 것이 맞지만, 자존심을 굽히지 않고 혼자 안고 갔던 것이 문제였던 것 같다.

**Comment by shinsy1023** [comment]
백엔드와 프론트엔드 사이에 소통이 없어, 서로간에 어떠한 진전이 있는지 제대로 파악하지 못하고 자신들의 할 일에만 바빠 말해주지 않아도 외부에서 얼마든지 파악할 수 있었던 이슈임에도 불구하고 파악하지 못했다.

**Comment by stevemg** [comment]
작업을 하면서 어디까지가 이슈인가를 고민했었고, 혼자서 판단해서 말을 안한 경우가 있었다.

**Comment by Hann** [comment]
https://github.com/Nansogong/Attendance-System/issues/103 이와 비슷한 이슈

**Comment by hsilnam** [comment]
프로젝트에서 합의된 함수이름 부분에서 더 직관적일것 같아 이름을 바꿨던 변경사항을 잘 말하지 않았다.
