### ISSUE TITLE
각 기능에 대한 의견 조율은 잘 되었는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#103]

**Comment by Hann** [comment]
설계떄는 잘 됐으나 이슈공유가 잘안되는 이유로 개발 중에는 잘 안된 것 같다.

**Comment by jaeseung91** [comment]
마찬가지로 이슈 공유가 원활하지 않았기 때문에 의견 조율도 잘 되지 않았던 것 같다.
의견 조율이 잘 되기 위해서는 팀원과의 지속적인 소통과 합의된 내용에 대해서는 명심하고 있어야 할 것이다.

**Comment by shinsy1023** [comment]
팀원들이 모여서 다같이 합의를 본 내용이 제대로 리마인드가 되지 않아, 변경되었거나 합의 된 내용이 제대로 적용되지 않았던 것 같다.

**Comment by Hann** [comment]
프로젝트를 매니징하는 입장에서는
설계때 합의된 내용을 충분히 이해하고 있고 회의 전까지는 다 숙지하고 회의에 참가해야할 것같다.

**Comment by shinsy1023** [comment]
이 이슈를 해결하기 위해서 어떠한 점이 도중에 변경되었는지, 어떤 기능을 어떤 이름으로 어떤 내용을 가지고 만드는 것인지에 대해 모델링 해둔 문서를 계속해서 참고하면서 개발해야 할 것 같다.

**Comment by stevemg** [comment]
항상 회의를 하고 그 다음에 회의에 대한 내용을 숙지를 못하여 의견 조율이 잘 안됬다.
