### ISSUE TITLE
Test Case는 도움이 되었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#104]
https://github.com/Nansogong/Attendance-System/issues/58 이 회고를 한 후에 마음이 바뀌었는지..

**Comment by shinsy1023** [comment]
일단 테스트케이스를 작성해두면 본문의 코드를 작성하면서 계속해서 코드의 적합성을 파악할 수 있으므로 유용했다.

**Comment by hsilnam** [comment]
기능을 만들 때마다 test case를 짜야해서 시간이 오래 걸린 면도 있지만 코드가 잘 돌아가는지 그때그때 확인 할 수 있어서 좋았다. 그리고 나중에 감이 잡히면 속도가 빨라져서 시간면으로도 괜찮았던 것 같다.

**Comment by Hann** [comment]
테스트 케이스를 임의로 변경한 사례도 있었지만, 팀리뷰를 통해 찾아냈다.
초반에 테스트케이스를 익히는데 시간이 오래걸렸을 뿐, 후에는 개발에 도움이 됐다.

**Comment by stevemg** [comment]
큐유닛을 통해 테스트 케이스 작성을 하려했지만, 예제로 밖에 사용을 못해봐서 test case 를 직접 작성하고 사용하지 않았다. 하지만, test.py 를 통해 내가 수정,커밋 할 때 마다 test case가 돌아 에러유무를 쉽게 판단할 수 있어서 유용했다.

**Comment by jaeseung91** [comment]
프론트에서는 QUnit을 사용하려다가 안쓰게 되었지만, py.test를 사용해본 결과 코드의 전체적인 흐름이 제대로 돌아가는지 알 수 있어서 편리했다. 익숙해지는데 시간이 조금 걸리더라도 나중에는 꼭 사용해야겠다.
