### ISSUE TITLE
원격회의 장단점

### ISSUE THREAD

**Issue by jaeseung91** [Nansogong/Attendance-System#106]

**Comment by stevemg** [comment]
장점 : 장소에 구애받지 않는다. 
단점 : 회의 집중도가 떨어진다.
다음에 이런경우가 있을때에는 MM를 회의 집중도를 해결하기 위해 각자 작성하는 편이 좋을거 같다.

**Comment by Hann** [comment]
멀리있는 사람이 오는데 부담이 있어서 그점에서는 좋았다.
다만, 이슈를 충분히 전달받지 못하는 것 같다.
페어프로그래밍은 원격보다는 붙어서 하는게 좋은 것 같다.
다음부터 가급적이면 회의는 모여서 할것같다.

**Comment by jaeseung91** [comment]
장점 : 다들 물리적으로 가까이 있지 않기 때문에 오기 힘든 경우나 많이 떨어져 있을 경우, 장소나 시간에 구애받지 않고 진행할 수 있었다.
단점 : face-to-face로 하는 것보다는 전달이 다소 떨어지는 것 같다.

**Comment by hsilnam** [comment]
같은장소에 있지않더라도 회의를 할수있어서 편했다
 그림을 그려서 설명해야 하는부분에서는 불편했다
