### ISSUE TITLE
프로세스 모델은 잘 지켜졌나?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#107]
https://github.com/Nansogong/Attendance-System/issues/110
https://github.com/Nansogong/Attendance-System/issues/105
https://github.com/Nansogong/Attendance-System/issues/108
https://github.com/Nansogong/Attendance-System/issues/106

**Comment by Hann** [comment]
https://github.com/Nansogong/Attendance-System/issues/110

**Comment by Hann** [comment]
테스트와 페어프로그래밍과 격일회의를 잘 지켜졌던 반면
투두두잉던은 잘 안된 것 같다.  격일 회의때 이슈가 잘 공유되지 않았던 문제도 있었다.

**Comment by Hann** [comment]
다음번에 매니징을 할 기회가 있으면 더 지금보다 더 강하게 압박을 해야겠다

**Comment by shinsy1023** [comment]
전체적으로 잘 흘러갔지만 데일리 미팅에서의 이슈 공유와 ToDo-Doing-Done 관리가 제대로 되지 않았다.
각자가 이슈를 솔직히 공유하고, 카드를 관리하는 등의 버릇을 들이는 것이 중요할 것 같다.

**Comment by stevemg** [comment]
Todo-Doing-Done 이 잘 안됬는데, 이를 잘 지켜진 격일 회의때 마다 Todo-Doing-Done도 같이 카드 생성을 하는게 좋을거 같다

**Comment by hsilnam** [comment]
Scrum의 카드 옮겨놓는것, 생성하는 것에서 todo doing done이 잘 되지 않았다.
 이틀마다 진행한 데일리 미팅은 꾸준히 잘 했다.
 페어프로그래밍은 장점은 많았지만 중간에 막히거나 서로시간이 맞지않으면 개발이 늦어진적이 있었다. 긴 프로젝트였으면 썼을듯 하다.

**Comment by jaeseung91** [comment]
TDD와 Pair Programming, 변형된 daily meeting은 비교적 잘 진행되었으나
Todo-Doing-Done 은 잘 되지 않았다. 아마 다음에 한번 더 하게 되면 이번 프로젝트보단
능숙하게 진행되지 않을까 싶다.
