### ISSUE TITLE
카드를 만드는것이 부담인가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#108]

**Comment by shinsy1023** [comment]
부담은 아니고 일정을 일일이 챙기는 것이 익숙치 않아 제때 생성하는 일이 적었다.

**Comment by Hann** [comment]
일정을 관리하는데에는 코드 뿐아니라 무엇을 하는지에 대한 카드가 너무 중요하다.
다음에는 나를 포함한 팀 모두가 익숙해졌으면 좋겠다.

**Comment by hsilnam** [comment]
카드를 만드는 것보다는 습관이 안되어서 까먹고 신경을 잘 못썼다. 그리고 혼자 개발하는 것에 익숙하다보니 혼자서만 일을 진행하고 카드를 작성하지 않고 나중에 추가했던 적도 있다.

**Comment by jaeseung91** [comment]
개발할 때 여러가지 참고해야할 사항과 관련 문서들을 켜놓고 작업을 하다보니 익숙하지 않아 자꾸 잊었다.

**Comment by stevemg** [comment]
일정에 맞춰서 카드를 만드는것을 까먹는 경우가 많이 있었다. 팀 프로젝트로 Git을 쓰는것도 처음이여서 카드생성이 더 익숙치 않았다.
