### ISSUE TITLE
러닝 코스트는 높았는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#109]

**Comment by Hann** [comment]
테스트케이스 만드는 것과 travis 셋팅과 cli로 디플로이하는 스크립트 짜는 것은 러닝코스트 있었다.
높다고 보지는 않는다.

**Comment by shinsy1023** [comment]
테스트케이스 작성법을 익히는데 오래 걸렸고, 백엔드를 처음 해봐서 구조를 익히는데 어려움이 있었다.
실제로 초반 2~3주간은 간단한 기능임에도 마일즈스톤의 스코프를 완료하지 못했다.

**Comment by stevemg** [comment]
경험이 부족하여 bootstrap, js, jquery등 러닝코스트가 높았다고 생각한다. 그래서 마일드스톤 스코프를 지켜가지 못했다.

**Comment by hsilnam** [comment]
flask, testcase와 백엔드를 처음해봐서 공부하고 코드를 이해하고 쓰는데 시간이 오래 걸려서 scope가 계속 연기 되었다.

**Comment by jaeseung91** [comment]
테스트케이스 작성에 대한 러닝 코스트가 컸다.
