### ISSUE TITLE
UML을 만든 상태에서 CRC를 만드는 것은 오버헤드가 크지않았는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#11]

**Comment by Hann** [comment]
CRC를 만들었다면 Class Diagram을 굳이 할필요가 없었을 것 같다.

**Comment by jaeseung91** [comment]
크지 않았으나, 굳이 UML을 만든 단계에서 CRC를 작성할 필요까진 없었다.

**Comment by stevemg** [comment]
굳이 필요한지 모르겠다. 클래스 다이어그램이 있는상태에서 CRC를 작성했기때문에 오버헤드가 발생했다.

**Comment by shinsy1023** [comment]
UML의 일종인 Class 다이어그램을 작성하여 그것을 참고하여 작성하면서 많은 시간을 소모하진 않았으나 작성하면서 이것을 할 필요가 없었다고 판단된다

**Comment by hsilnam** [comment]
UML을 만들 때 생각할 것도 많고 복잡해서 시간도 오래 걸리고 힘들었었는데 CRC를 직접해보니 좀 더 체계적이고 쉽게 정리하고 어느부분이 잘못 생각되었는지 확인해볼 수 있었다. 이것을 UML하기 전에 했다면 더 효율적으로 할 수 있었을 것 같다.

**Comment by Hann** [comment]
나중에 프로젝트를 할때는 둘중하나를 선택해서 할 것 같다.
