### ISSUE TITLE
스코프의 우선순위는 제대로 매겨졌는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#110]

**Comment by Hann** [comment]
view sagi부터 만들었으면 피드백을 받았을텐데
유저가 액션하는 순서로 개발을 해서 피드백을 받지못했다.

**Comment by jaeseung91** [comment]
처음에는 우선순위에 대한 중요성을 잘 몰랐으나 중반부를 지나면서 그리고 교수님과의 면담 후에 크게 느꼈다. 만약 우선순위를 잘 맞췄다면 개발을 끝마치지 못했더라도 핵심 부분을 보여줄 수 있었을 것이다.

**Comment by stevemg** [comment]
요구사항을 제대로 도출했는가에 대해 생각이 들었다. 요구사항을 우선순위로 도출했다면 Scope의 우선순위도 따라갔을거 같다.

**Comment by shinsy1023** [comment]
주요 기능을 먼저 작성했어야 우리 어플리케이션이 무엇을 하는 것인지 보여줄 것이 있었을 텐데, 다른 대다수의 웹페이지에도 있는 기능들을 우선적으로 작성하여 우리 어플리케이션만의 무언가를 보여줄 수 없었다.

**Comment by hsilnam** [comment]
우선순위를 신경쓰지않고 단순히 스코프를 유저가 동작하는 순으로 했기때문에 가장 핵심이 되는 부분을 전부 개발하지 못한 것 같다.

**Comment by shinsy1023** [comment]
요구사항 도출 단계에서 프로젝트에 어떤 기능들이 중요한지를 파악하고 우선순위를 주어야 한다.
