### ISSUE TITLE
미팅미닛을 매니저가 쓰는게 좋았는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#111]

**Comment by Hann** [comment]
내용을 애기하면서 기록하기가 쉽지않았다. 다른사람이 썼으면 좋았을 것 같다

**Comment by stevemg** [comment]
가끔 매니저 대신 MM을 쓰는데, 애기하면서 기록하기가 역시 쉽지않았다. 그래서 각자 MM을 작성하되 자신이 의견내는 부분은 다른사람에게 대신작성을 맡겨서 나중에 모든사람의 MM을 합치는게 좋은 방법이였을거 같다.
