### ISSUE TITLE
파이썬을 쓰는것은 어려웠나?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#112]

**Comment by hsilnam** [comment]
파이선의 딕션너리 부분과 함수의 특성을 정확하게몰라서 초반에 좀 코드 해석과 사용이 힘들었지만 그것을 제외하고는 자료형같이 다른 언어와 달리 신경써야하는 부분이 적어 편했다

**Comment by shinsy1023** [comment]
파이썬을 너무 오랜만에 써봐서 import 기억하는데도 오래 걸렸다. 근데 일단 시작하니 몸이 알아서 문법을 써서 크게 어렵지 않았다.

**Comment by Hann** [comment]
파이썬3은 1학년때 배웠다고 생각해서 선택했는데 적응하는데 시간이 걸리는 모습을 봐서 아쉬웠다.

**Comment by jaeseung91** [comment]
어렵다기 보다는 너무 오랜만에 썼기 때문에 처음 접한 것만큼 익숙하지 않아서 적응하는데 시간이 다소 걸렸다.

**Comment by stevemg** [comment]
오랜만에 사용을 해서 적응과 함수를 기억하는데 오랜 시간이 걸렸다.
