### ISSUE TITLE
깃의 브랜치, 혹은 피쳐 관리는 제대로 되었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#113]

**Comment by Hann** [comment]
피처를 너무 크게 따서 머지를 잘 안하는 문제가 있었다.
그리고 피처를 땄으면 커밋을  리모트에 푸시하는 것도 좋은방법인것같다

**Comment by jaeseung91** [comment]
피쳐 하나하나를 너무 크게 만들었기 때문에 머지하는데에 시간이 오래걸렸다. 그렇기 때문에 다음에는 작게 따서
커밋, 푸시를 자주 하도록 해야겠다.

**Comment by stevemg** [comment]
깃이 처음이였고, 익숙치도 않아서 피쳐를 따도 이것을 언제 커밋하고 언제 브렌치 종료를 하는지도 판단하기 힘들었다. 또한 피쳐를 너무 크게 잡아서 관리가 잘 되지 않았다. 다음엔 한 파일당 수정작업을 할때마다 커밋을 해야겠다.

**Comment by shinsy1023** [comment]
백엔드에선 피쳐의 범위를 적당히 잡아서 심각하게 막힐 때를 제외하곤 주기적으로 커밋이 올라갔다고 생각한다.

**Comment by hsilnam** [comment]
깃을 쓰는 것에 대한 두려움이 사라졌고 기본적으로 어떻게 쓰는지 알게되었다.
기능을 만들 때 까먹지 않고 feature를 따는 습관과 commit하기 전에 실수로 파일이 사라지지 않도록 stash에 저장하는 습관을 길렀다.
feature을 자주자주 local에 commit하는 건 잘 못했지만 일배분(feature 배분)과 머지는 잘 처리한 것 같다.
