### ISSUE TITLE
일정 목록 관리는 제대로 되었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#114]

**Comment by Hann** [comment]
캘린더 추가는 당일날 한 적도 있었다.
공지가 늦어져서 미안했던 적도 있었다. 바로바로 회의가 끝나마자 다음 회의를 추가하는게 좋은 방법인것같다.

**Comment by hsilnam** [comment]
캘린더 추가가 습관이 되지 않아 당일날 추가하거나 나중에 추가한 적이 있었다.
당일날 회의 시간이 정해진 날도 있어서 회의는 그 날 회의가 끝나자 마자 정하고 나서 추가하는 것이 나을 것 같다.

**Comment by shinsy1023** [comment]
페어프로그래밍을 할 적에 회의 중에 캘린더에 추가하면 다행이고, 회의 끝나고 한참 지나고 나서 캘린더에 등록한 일이 많아 PM의 참여가 힘들었다.
일정 관리를 제대로 해야할 것이다.

**Comment by jaeseung91** [comment]
원래는 일정이 생기면 다이어리에 수기로 작성을 했었는데 캘린더 앱을 사용하여 일정을 등록해야 했기에 깜박한 경우가 있었다. 습관이 들여져야 할 부분인 것 같다.

**Comment by stevemg** [comment]
페어프로그래밍을 진행할 시, 프론트끼리만 얘기가 되서 캘린더에 추가하는걸 까먹고 추후에 추가하는 경우가 많았다. 격일 전체 회의나 프론트회의때 다음 회의를 캘린더에 추가해야겠다.
