### ISSUE TITLE
미팅미닛에 필요한 정보가 전부 담겼었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#115]

**Comment by Hann** [comment]
혼자서 적고 혼자서 진행하려보니 놓치는 부분이 많고 모두 적어야되는가라는 고민이 있었다.
다음에는 진행자가 작성을 하지 않는 것이 좋을 것 같다.

**Comment by stevemg** [comment]
매니저가 휼륭하게 정보를 담아주었다. 하지만 앞으로는 MM을 모두다 적되, 자신의 의견말할때에는 적지 않고 나중에 서로 적은것을 합해서 MM을 만드는게 좋을거같다.

**Comment by hsilnam** [comment]
녹음해서 적어본적이있는데 얼마나 자세히 적어야하는 건지 고민했다.

**Comment by jaeseung91** [comment]
미팅 미닛에는 그래도 많은 정보들이 들어갔다고 생각한다. 해야할 일들이 생각이 나지 않는 경우, 이슈들이 생각나지 않는 경우 미팅 미닛의 도움을 많이 받았다.
