### ISSUE TITLE
프로젝트의 퀄리티는 어떠한가

### ISSUE THREAD

**Issue by shinsy1023** [Nansogong/Attendance-System#117]
3.4.1 Software Constraints
---
- Coding with Python.(파이썬으로 코딩한다.)
- Conventions follow PEP8.(컨벤션은 follow PEP8.)
- The Database API uses mysql-python.(Database API는 mysql-python을 사용한다.)
- Template Engine uses Jinja2.(Template Engine은 Jinja2를 사용한다.)

3.5.1 Security
---
- The password is encrypted and stored.(비밀번호를 암호화하여 저장한다.)
- Students will not be able to see other people's attendance information.(학생들은 다른
사람의 출결 정보를 볼 수 없다.)

3.5.2 Reliability
---
- AWP Service Downtime does not exceed 4 hours.(AWP의 Service 정지 시간이 4 hours를 넘기지 않는다.)

3.5.3 Availability
---
- The device on which the web browser is running must be connected to the Internet.(Web browser가 실행되는 device는 인터넷에 연결되어야만 한다.)

**Comment by Hann** [comment]
3.4.1 Software Constraints
- Coding with Python.(파이썬으로 코딩한다.)
- Conventions follow PEP8.(컨벤션은 follow PEP8.)
- The Database API uses mysql-python.(Database API는 mysql-python을 사용한다.)
- Template Engine uses Jinja2.(Template Engine은 Jinja2를 사용한다.)

**Comment by shinsy1023** [comment]
대다수의 기능이 구현되지 못하여, 회고할 요소가 없는 것들이 많이 있다.

**Comment by Hann** [comment]
- 파이썬 코딩 함
- PEP8 따름 
- mysql-python 사용
- jinja2 사용

- 암호화 함
- 구현x
-  디플로이 x

- 인터넷연결 필수

**Comment by stevemg** [comment]
처음에 FURPS 퀄리티 측정 등을 염두에 두고 시작한 것이 아니여서 회고는 SRS에 적은 부분으로만 할 수 있었다. 또한 기능구현이 거의 없어서 회고할 수 있는 퀄리티 요소가 없다.

**Comment by Hann** [comment]
Wow
