### ISSUE TITLE
Requirement Analysis는 잘 되었는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#118]

**Comment by Hann** [comment]
초기에 교수님과 면담을 통해서 도출했으나, 작업하면서 딜리버리를 가져가지 못해서 피드백을 받지못했다. 그래서 요구사항을 더 구체적으로 분석하지 못했다고 생각한다.

**Comment by shinsy1023** [comment]
요구사항을 분석하고, 이후 Stakeholder와의 소통을 통해 피드백을 받으려 하였으나 그러지 못해 고객의 요구사항을 전부 파악했는지 알 수 없고, 도출해낸 요구사항을 제대로 분석해내지 못해 이후 프로젝트를 진행하면서 계속해서 프로그램의 구조나 기능에 대해 수정을 가하게 됐다.

**Comment by hsilnam** [comment]
scope이 어느정도 진행이 되고나서 교수님과 면담을 통해 피드백을 받고 요구사항을 도출하고 분석했어야했지만 계속 미뤄져서 부족했던 것 같다.

**Comment by stevemg** [comment]
요구사항 분석의 주 목적이 고객의 원하는것이 잘 반영이 되었는가? 에 대해서 요구사항이 전부 파악했는지 확정지을 수 없다. 교수님과 면담을 통해서도 요구사항을 도출했지만 작업하면서 명확하게 반영을 하지 못한거 같다. 이후 프로젝트에서는 고객의 요구사항 파악을 위해서 프로세스를 프로트타입을 반영하는것도 좋은 선택일것 같다.

**Comment by jaeseung91** [comment]
면담을 통한 교수님의 피드백으로 도움은 많이 되었지만, 한 번의 면담으로 requirement가 제대로 도출되기는 어렵다고 생각한다. 설사 한 번에 피드백으로 requirement를 도출하려 했다면, scope를 상세하게 가져가서 좀 더 정확하게 조언을 받았어야 하지 않았나 싶다.
