### ISSUE TITLE
PM이 주로 Back-end에서 개발을 진행했는데 이러한 판단이 적절했는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#119]

**Comment by Hann** [comment]
백엔드 셋팅이 필요한 부분이 있고 주로 백엔드가 먼저 기능을 내놓아야해서 주로 벡엔드 쪽을 진행했는데, 진행이 느린쪽에 더 집중하는게 옳았던 선택같다.

**Comment by jaeseung91** [comment]
판단이 적절하다고 생각하지 않는다. Back-end에서 고려할 부분이 많아 PM이 그쪽으로 붙은 것인데, Front-end에서 부족함이 느껴졌을 때, 바로 얘기했어야 했다.

**Comment by shinsy1023** [comment]
주로 Back-end에서 개발했다고는 하지만 이전까진 Travis나 fabric 설정, 서버 세팅 등의 기능에 집중하였기 때문에 Back-end에 대한 절대적인 기여도가 매우 크진 않다고 생각한다. 주로 Back-end에서 막히는 부분만을 해결하는 식으로 기여하였기 때문에 큰 문제가 없었다고 생각한다.

**Comment by stevemg** [comment]
그렇지 않다.  Front-End 개발이 느려진 것에 대해서 PM에게 솔직히 말을 못한게 아쉽다.
