### ISSUE TITLE
프로젝트의 규모는 적절했는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#120]

**Comment by jaeseung91** [comment]
팀원들의 전반적인 상황들을 고려했을 때 적절했던 것 같다.

**Comment by Hann** [comment]
적절했다. 풀타이머의 경우라면프로젝트의 사이즈가 작다고 생각하지만, 우리는 파트타이머보다 시간이 없었다.  그래서 지금보다 작은 경우라면 유의미한 결과를 얻기가 힘들었을 것 같다.

**Comment by stevemg** [comment]
클래스에서 요구하는 규모 자체는 적절했지만, 내 역량으론 규모가 큰 부분이라고 생각한다.

**Comment by shinsy1023** [comment]
우리가 이번 강의에서 해야 했던 프로젝트의 규모에 적절한 프로젝트였다고 생각한다.

**Comment by hsilnam** [comment]
해야하는 일의 양을 봤을 때 프로젝트의 규모가 적절했다고 생각한다
