### ISSUE TITLE
Pair Programming은 괜찮았는가?

### ISSUE THREAD

**Issue by hsilnam** [Nansogong/Attendance-System#27]

**Comment by hsilnam** [comment]
장점 : 공통된 작업에 대해 같이 생각할 수 있게 되어 혼자 생각할 때 놓쳤던 부분 채울 수 있고 애매하던 부분을 좀더 확실히 할 수 있다.
단점 : 페어프로그래밍은 같이 작업을 해야하는데 둘 다 바쁠 경우 그 시간을 맞추기 어려워 둘다 비는 시간을 찾을 때까지 일이 지체될 수 있다.

**Comment by Hann** [comment]
개개별에게 공지 안해도 돼서 좋았음

**Comment by Hann** [comment]
서로 모르는 경우에 같이 찾아 볼 수 있어서 좋았다.

**Comment by jaeseung91** [comment]
시간조율의 문제만 아니면 장점이 굉장히 많은듯 하다.

**Comment by Hann** [comment]
재승: 한 코드에 대한 이해도는 높은 것 같다

**Comment by shinsy1023** [comment]
각자의 시선으로 같은 코드를 보기 때문에 허점이나 불필요한 부분 등을 비교적 수월히 찾아낼 수 있다는 것이 상당히 편했다.

하지만 나, 혹은 현실이 누나가 어떠한 코드를 이해하지 못했을 때 서로에게 설명하느라 낭비되는 시간이 있었다.
