### ISSUE TITLE
register 예외사항 처리

### ISSUE THREAD

**Issue by hsilnam** [Nansogong/Attendance-System#34]

**Comment by hsilnam** [comment]
예외사항
1. 중복된 고유번호(user_num)을 적었다
2. 필수요소를 다 적지 않았다

**Comment by shinsy1023** [comment]
[link](https://github.com/Nansogong/Attendance-System/commit/d8cf4bf8a16bfd7f20a36cb8f5ab5628628b97ed)에서 고유번호와 이메일 중복 해결

**Comment by shinsy1023** [comment]
[link](https://github.com/Nansogong/Attendance-System/commit/7432a87a6d72daebfbf910d52a5bba26a717b24e)에서 필드에 값이 입력되지 않았을 경우 해결
