### ISSUE TITLE
하는 일에 비해서 일정이 빠듯했는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#55]

**Comment by stevemg** [comment]
시간이 부족했다. 우선 아는것이 부족해서 러닝코스트에 시간이 많이 들었고, UI구상 결정에 있어서 확신이 들지 않았다. 또한 페어프로그래밍을 접목해서 작업이 더뎌진 요소도 있다.

**Comment by hsilnam** [comment]
모르는 부분이 많아서 막히는 부분이 있고 찾아서 공부하는데도 많은 시간이 걸렸다.

**Comment by Hann** [comment]
서버셋팅을 늦게해줘서 다들 일을 늦게 시작한 것 같다. 1주 정도 걸렸기 때문

**Comment by jaeseung91** [comment]
접해보지 않은 부분들이 있어 실제로 접해보니 계획했던 것보다 생각보다 시간이 걸렸던 것 같다.
