### ISSUE TITLE
다음 일정을 잘 하려면 어떻게 해야할까?

### ISSUE THREAD

**Issue by jaeseung91** [Nansogong/Attendance-System#57]
회고 내용:
- 페어프로그래밍을 고친다
- 일정을 줄인다
- 테스트 케이스를 없앤다

**Comment by Hann** [comment]
현실: 테스트 케이스는 들고가야한다.

**Comment by Hann** [comment]
재승: 페어프로그래밍은 들고가야한다

**Comment by Hann** [comment]
마일 스톤 수정함
 오늘까지의 일을 잡고, 다음주에는 더 잘게 쪼갠 일을 마일스톤으로 가져가는 것으로 함.
