### ISSUE TITLE
테스트 코드 짜는건 어려운가? 쉬운가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#58]

**Comment by Hann** [comment]
현실: 한국어 자료가 별루 없다

**Comment by Hann** [comment]
진수: 백엔드 개발하면서 이것저것 많이 뜯어고쳤는데 그때마다 빨간불들어와서 쉽게 사이드 이펙트를 알 수 있어서 좋았다. 다음에 프로젝트를 한다면 무조건 쓸 것 같다

**Comment by Hann** [comment]
진수: 그전까지는 부담이 돼서 악몽에 시달렸으나, 생각보다 할만했다

**Comment by shinsy1023** [comment]
가면 갈수록 점점 익숙해지고 비슷한 기능을 하는 페이지들은 이전의 메소드들을 참고해 금방 만들 수 있어서 익숙해지면 질 수록 상당히 빠른 속도로 테스트케이스를 작성할 수 있을 것 같다. 처음은 어렵지만 갈수록 매력이 느껴지고 편리한 방법이라고 생각함
