### ISSUE TITLE
원격으로 페어 프로그래밍 하는 법 조사

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#6]

**Comment by shinsy1023** [comment]
http://www.saros-project.org/saros-for-intellij

**Comment by Hann** [comment]
https://floobits.com/help/plugins/intellij

**Comment by hsilnam** [comment]
https://www.quora.com/What-are-the-best-tools-for-remote-pair-programming
-> 여러가지 원격 페어프로그래밍 도구들

그 중에서 내가 뽑은 것
https://screenhero.com/ 
->[Screenhero] : joined slack
http://remotepairprogramming.com/ 
->[motepair] : Atom editor package
뽑은 이유 -> 우리가 자주 사용하는 툴에 더해진 개념이라 익숙하고 편하게 잘 쓸 수 있을 것 같아서
