### ISSUE TITLE
일정은 적절했는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#63]

**Comment by Hann** [comment]
페어 프로그래밍이 나쁜건 아닌데, 지금은 개발의 산출물이 적다고 생각해서 변화가 필요하다고 생각한다

**Comment by Hann** [comment]
수용: 시간을 잡고, 그전까지 코드에 수정을 가할 수 없으니깐 집에서 컴퓨터 열고 하는것에 비해서 절대적인 시간이 부족했다.

**Comment by Hann** [comment]
현실: 어느정도까지 건드려야하는지, 잘 몰랐다. 로직 코드는 만나서해야한다는 강박관념이 있어서 생각만하려니깐 모르는것도 있었다

**Comment by jaeseung91** [comment]
질문과는 조금 안맞을 수 있는데, 일정이 적절했는가보다는 페어프로그래밍에 대해서 다시 한 번 생각해보았다. 물론 페어 프로그래밍의 장점은 있지만, 한 그룹의 멤버들이 시간을 맞추는 것이 가장 장애물이 된 것 같다. 개인적으로 되는 시간이 각각 다른데 그 시간에 맞추어야 하고, 한 그룹이 같은 곳에서 막힐 경우 시간이 두 배로 소요가 되는 것 같아 절대적인 시간이 부족하다고 느껴졌다.

**Comment by stevemg** [comment]
시간 맞추는게 가장 어려운거 같다.

**Comment by Hann** [comment]
지금 일정을 1주 미루고, 각자가 개발하고, 기능단위로 일을 맡는것으로한다.
