### ISSUE TITLE
Unit Test에 대해서 조사해보기

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#7]

**Comment by stevemg** [comment]
도서관 책 빌리기 - "테스트주도개발(Kent Beck)"

**Comment by Hann** [comment]
여기에 파이썬 유닛테스트 라이브러리가 정리되어있네
https://www.fullstackpython.com/unit-testing.html

**Comment by jaeseung91** [comment]
pair programming :
- gotty : https://www.joinc.co.kr/w/man/12/docker/tmux
- teamviewer : http://comterman.tistory.com/548
TDD : 
- pyunit : http://serious-code.net/doku/doku.php?id=kb:pyunit
