### ISSUE TITLE
Design Model 선택은 적절했는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#95]

**Comment by Hann** [comment]
경우에는 클래스 다이어그램 그렸는데, 모두가 합의된 내용이고 그리고 특히 메소드 명에 대해서 각기 다른 이름을 정한게 아니라서 좋았음

**Comment by stevemg** [comment]
state diagram을 통해서 프로그램 흐름도를 명확히 알 수 있어서 템플릿작성할 때 도움이 되었다.
다음번에도 한정된 유저와 유저의 흐름이 일정한 프로젝트가 있으면 유저스토리를 건너뛰고 바로 state diagram을 작성할것이다.

**Comment by Hann** [comment]
유저스토리 만들었으면 오버헤드였을 듯
