### ISSUE TITLE
User Story를 건너뛰었던게 괜찮은 선택이었을까?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#96]

**Comment by jaeseung91** [comment]
괜찮은 선택이었다고 생각한다.
플로우의 경우의 수가 많지 않고 그 길이가 길다면 user story를 사용하는 것이 맞다고 생각했지만
우리 프로젝트의 경우 플로우의 경우의 수가 굉장히 많기 때문에 건너뛰는게 옳았다고 생각한다.

**Comment by Hann** [comment]
스테이트 머신 다이어그램에서 충분히 커버된것같다.
유스케이스는 만들었으니 초기단계에서 이해는 된 것 같고, 
후에 사용할때는 스테이트머신다이어그램을 보아서 유저스토리의 불편함을 겪지못했다.

**Comment by shinsy1023** [comment]
Usecase를 만들 때 긴 시간이 걸린 원인에 User story의 부재가 약간이나마 있는 듯 하지만 Usecase를 만든 이후부턴 볼 일이 없어져 부재가 크게 느껴지지 않았다.
