### ISSUE TITLE
Use Case는 도움이 되었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#97]

**Comment by shinsy1023** [comment]
팀원간의 소통과, 프로그램의 기반을 다지고 그 내용을 공유하는데 있어 상당히 도움이 되었다고 생각한다.

**Comment by stevemg** [comment]
use case를 통해 uml과 state diagram을 도출하는데 있어서 큰 도움이 되었다고 생각한다.

**Comment by Hann** [comment]
초기 단계에는 use case diagram이 눈에 잘 들어왔다. 서로가 합을 맞추는데 도움이 되었다.

**Comment by jaeseung91** [comment]
후반부로 가면서는  use case를 거의 보지 않고 진행하였지만, 그 과정에서 state machine diagram을 만들기 위한 것임에는 필요했다고 생각한다.
