### ISSUE TITLE
CRC는 부족함이 없었는가?

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#98]

**Comment by Hann** [comment]
이때는 모델 중심으로 만들었는데 지금과는 너무 다른 구조다. 프로젝트가 지금보다 더 추상적이었다고 생각한다.

**Comment by jaeseung91** [comment]
나중에 만들어진 class diagram과 차이가 꽤 났기 때문에 부족함이 있었다고 생각한다.

**Comment by stevemg** [comment]
요구사항 도출이 부족해서 지금보다 부족한 부분이 있었다고 생각한다.

**Comment by shinsy1023** [comment]
이전의 절차에서 분석이 제대로 되지 않아 우리가 무엇을 원하는지, 어디에 어떤 요소들이 들어가야 하는지, 무엇이 필요한건지 등의 필요사항들이 제대로 추출되지 않았고, 그에따라 CRC와 Class diagram 작성 사이의 기간에 추가적인 협의가 필요해져서 둘 사이에 차이가 크게 있었다고 생각한다.

그러므로 CRC의 작성에 부족한 점이 많았다고 생각한다.
