### ISSUE TITLE
Use Case 잘 뽑아내었는가

### ISSUE THREAD

**Issue by Hann** [Nansogong/Attendance-System#99]

**Comment by hsilnam** [comment]
초반에 use case 잘 뽑아 내진 못했던 것 같지만 나중에 개발을 하면서 개선하고 더 채워졌던 것같다

**Comment by Hann** [comment]
디자인 모델링에서 도출된 메소드와 비교해 볼때는 다른 점이 많아서 잘 뽑아냈다고 생각되지는 않지만
그 과정으로 가기에 도움을 주었다고 생각한다
